#!/usr/bin/env node

var program = require('commander')

program
  .command('about', 'Publish a message of the type about')
  .command('post', 'Publish a message')
  .command('contact', 'Publish a contact message')
  .parse(process.argv)

if (!program.args.length) program.help()
