#!/usr/bin/env node

var program = require('commander')
var Connection = require('..')

program
  .option('--name <str>', 'Set your name')
  .option('--description <str>', 'Set your description in markdown. Be sure to quote for command line')
  .option('--image <hash>', 'Set your profile image. See "blob add" to add the image, get the hash')
  .parse(process.argv)

Connection((err, server) => {
  if (err) {
    throw err
  }

  server.whoami((err, keys) => {
    if (err) {
      server.close()
      throw err
    } else {
      var message = {
        type: 'about',
        about: keys['id']
      }

      if (program.name) {
        message['name'] = program.name
      }
      if (program.description) {
        message['description'] = program.description
      }
      if (program.image) {
        message['image'] = program.image
      }

      server.publish(message, (err) => {
        server.close()
        if (err) {
          throw err
        }
      })
    }

    server.close()
  })
})
